//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIV_PF_ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalleFactura
    {
        public int num_consecutivo { get; set; }
        public string codigo_factura { get; set; }
        public string codigo_producto { get; set; }
        public int cantidad { get; set; }
        public decimal valor_unitario { get; set; }
        public decimal total_linea { get; set; }
    
        public virtual factura factura { get; set; }
        public virtual producto producto { get; set; }
    }
}
