//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIV_PF_ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public int id_producto { get; set; }
        public string codigo_producto { get; set; }
        public string descripcion { get; set; }
        public decimal precio { get; set; }
        public string estado { get; set; }
        public int id_tipoProducto { get; set; }
    
        public virtual tipoProducto tipoProducto { get; set; }
    }
}
