//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIV_PF_ProyectoFinal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PIV_PF_Proyecto_Final_Entities : DbContext
    {
        public PIV_PF_Proyecto_Final_Entities()
            : base("name=PIV_PF_Proyecto_Final_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<detalleFactura> detalleFactura { get; set; }
        public virtual DbSet<factura> factura { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tipoProducto> tipoProducto { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<UsuarioRegistrado> UsuarioRegistrado { get; set; }
    }
}
