//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIV_PF_ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioRegistrado
    {
        public int id_usuarioRegistrado { get; set; }
        public string user { get; set; }
        public string password { get; set; }
        public string rol { get; set; }
        public int id_usuario { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
